[GRIFFIN-369] Bug fix for avro format in Spark 2.3.x environment
apache/griffin pull request #598
Opened 2022-01-18 12:58 UTC by lipzhu

**What changes were proposed in this pull request?**
Built in Avro format is released in Spark 2.4.0,https://issues.apache.org/jira/browse/SPARK-24768
For Griffin, we still need to convert the Avro to com.databricks.spark.avro in Spark 2.3.x environment. 

**Does this PR introduce any user-facing change?**
No.

**How was this patch tested?**
Unit Tests

2022-01-19 06:45 UTC, whhe approved these changes

2022-01-24 04:48 UTC, chitralverma requested changes

2022-01-24 04:48 UTC, chitralverma commented on measure/src/main/scala/org/apache/griffin/measure/datasource/connector/batch/FileBasedDataConnector.scala
> +  // built-in AVRO data source implementation is released in spark 2.4.0
Suggestion:

```suggestion
  // Use old implementation for AVRO format if current spark version is not 2.4.x and above
```

2022-01-24 04:50 UTC, chitralverma requested changes

2022-01-24 04:50 UTC, chitralverma commented on measure/src/main/scala/org/apache/griffin/measure/datasource/connector/batch/FileBasedDataConnector.scala
> +  if (format.equalsIgnoreCase("avro") && sparkSession.version < "2.4.0") {
```suggestion
  if ("avro".equalsIgnoreCase(format) && sparkSession.version < "2.4.0") {
```

2022-01-24 04:51 UTC, chitralverma approved these changes

2022-01-24 05:10 UTC, closed without merging